# Dependencias
FROM node:22-alpine3.21 AS deps

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

# Builder
FROM node:22-alpine3.21 AS build

ARG PRODUCTS_DATABASE_URL
ENV DATABASE_URL=$PRODUCTS_DATABASE_URL

WORKDIR /usr/src/app

## Copiar de deps, los módulos de node
COPY --from=deps /usr/src/app/node_modules ./node_modules

## Código fuente de la aplicación
COPY . .

RUN npx prisma migrate deploy
RUN npx prisma generate

## RUN npm run test
RUN npm run build

## Dependencias de producción
RUN npm ci -f --only=production && npm cache clean --force

# Docker Image
FROM node:22-alpine3.21 AS prod

WORKDIR /usr/src/app

COPY --from=build /usr/src/app/node_modules ./node_modules

## Copiar la carpeta de DIST
COPY --from=build /usr/src/app/dist ./dist
COPY --from=build /usr/src/app/generated ./generated
COPY --from=build /usr/src/app/prisma ./prisma

ENV NODE_ENV=production

USER node

EXPOSE 3000

CMD [ "node", "dist/main.js" ]